const data = {
  products: [
    {
      title: "Planes de Negocios",
      slug: "planes-de-negocios",
      description: "Planes de Negocios",
      category: "Asesoria Empresarial",
      image: "/images/AnalisisTecnico.jpg",
      cost: 250,
      price: 500,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Estudios de Factibilidad",
      slug: "estudios-de-factibilidad",
      description: "Estudios de Factibilidad",
      category: "Asesoria Empresarial",
      image: "/images/EstudiosFactibilidad.jpg",
      cost: 300,
      price: 600,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Perfiles de Inversiones",
      slug: "perfiles-de-inversiones",
      description: "Perfiles de Inversiones",
      category: "Asesoria Empresarial",
      image: "/images/PerfilesInversiones.jpg",
      cost: 200,
      price: 400,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Proyectos de Inversiones",
      slug: "proyectos-de-inversiones",
      description: "Proyectos de Inversiones",
      category: "Asesoria Empresarial",
      image: "/images/ProyectosInversiones.jpg",
      cost: 250,
      price: 500,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Corretaje de Inmuebles",
      slug: "corretaje-de-inmuebles",
      description:
        "Lograr los precios más adecuados, e inmuebles más idóneos, para ofertantes y demandantes del Mercado Inmobiliario",
      category: "Portal Inmobiliario",
      image: "/images/CorretajeInmuebles.jpg",
      cost: 300,
      price: 600,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Asesoria en Activos Financieros",
      slug: "asesoria-en-activos-financieros",
      description:
        "Información oportuna, para realizar Inversiones Financieras rentables con riesgos mínimos",
      category: "Asesoria Financiera",
      image: "/images/AsesoriaFinanciera.jpg",
      cost: 200,
      price: 400,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Gestión de Cartera de Inversiones",
      slug: "gestión-de-cartera-inversiones",
      description:
        "Gestion de Inversiones rentables, según nivel de riesgo adecuado para Clientes",
      category: "Asesoria Financiera",
      image: "/images/GestionCarteraActivosFinancieros.jpg",
      cost: 250,
      price: 500,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Fondos de Inversiones",
      slug: "fondos-de-inversiones",
      description:
        "Ofertar participaciones en Inversiones rentables, según nivel de riesgo adecuado para Clientes",
      category: "Productos Financieros",
      image: "/images/FondosInversiones.jpg",
      cost: 300,
      price: 600,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Letras, Pagares y Certificados de Mesa de Dinero",
      slug: "letras-pagares-mesa-de-dinero",
      description:
        "Ofertar participaciones en Inversiones rentables, según nivel de riesgo adecuado para Clientes",
      category: "Productos Financieros",
      image: "/images/MesaDinero.jpg",
      cost: 200,
      price: 400,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Panderos y Juntas de Efectivo",
      slug: "panderos-juntas-de-efectivo",
      description:
        "Ofertar participaciones en Juntos y Panderos, con la garantía de participantes solventes, sin impagos",
      category: "Productos Financieros",
      image: "/images/JuntasEfectivo.jpg",
      cost: 250,
      price: 500,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Lineas de Credits",
      slug: "lineas-de-Credits",
      description:
        "Prestamos en Efectivo a Prestatarios solventes, sin moras e impagos recurrentes",
      category: "Productos Financieros",
      image: "/images/LineasCredits.jpg",
      cost: 300,
      price: 600,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Criptomonedas",
      slug: "criptomonedas",
      description:
        "Medio de cambio y valor como resguardo ante inflación, confidencialidad y libre convertibilidad",
      category: "Productos Financieros",
      image: "/images/CriptoMonedas.jpg",
      cost: 200,
      price: 400,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: "Giros y Transferencias",
      slug: "giros-y-transferencias",
      description: "Transferencias de dinero, en forma confidencial y oportuna",
      category: "Productos Financieros",
      image: "/images/Transferencias.jpg",
      cost: 250,
      price: 500,
      brand: "Tec Data",
      rating: 4.5,
      numReviews: 10,
    },
  ],
};

export default data;
